name: Build test and deploy to Heroku

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version : '14'

      - name: Install dependency
        run: npm install

      - name: Build the project
        run: npm run build

    test:
      needs: build
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Setup NodeJS
          uses: actions/setup-node@v2
          with:
            node-version: '14'

        - name: Install dependency
          run: npm install

        - name: Run Tests
          run: npm test